# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: head.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='head.proto',
  package='proto',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\nhead.proto\x12\x05proto\"\x9a\x02\n\nPacketHead\x12\x11\n\tpacket_id\x18\x01 \x01(\r\x12\x11\n\tsign_type\x18\x02 \x01(\r\x12\x0c\n\x04sign\x18\x03 \x01(\r\x12\x0f\n\x07user_id\x18\x04 \x01(\r\x12\x10\n\x08src_addr\x18\x05 \x01(\r\x12\x10\n\x08\x64st_addr\x18\x06 \x01(\r\x12\x15\n\rdispatch_type\x18\x07 \x01(\r\x12\x13\n\x0bserver_type\x18\x08 \x01(\r\x12\x18\n\x10\x64ispatch_key_u64\x18\t \x01(\x04\x12\x17\n\x0fuser_session_id\x18\n \x01(\r\x12\n\n\x02id\x18\x0b \x01(\r\x12\x14\n\x0c\x63oroutine_id\x18\x0c \x01(\r\x12\x0f\n\x07hop_cnt\x18\r \x01(\r\x12\x11\n\tclient_ip\x18\x0e \x01(\r*\xd4\x01\n\x0c\x44ispatchType\x12\x16\n\x12\x44ISPATCH_TYPE_NONE\x10\x00\x12\x19\n\x15\x44ISPATCH_TYPE_BY_ADDR\x10\x01\x12\x18\n\x14\x44ISPATCH_TYPE_BY_MOD\x10\x02\x12\x19\n\x15\x44ISPATCH_TYPE_BY_RAND\x10\x03\x12\x1a\n\x16\x44ISPATCH_TYPE_BY_CHASH\x10\x04\x12#\n\x1f\x44ISPATCH_TYPE_BY_STICKY_SESSION\x10\x05\x12\x1b\n\x17\x44ISPATCH_TYPE_BY_OBJECT\x10\x06\x62\x06proto3'
)

_DISPATCHTYPE = _descriptor.EnumDescriptor(
  name='DispatchType',
  full_name='proto.DispatchType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='DISPATCH_TYPE_NONE', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DISPATCH_TYPE_BY_ADDR', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DISPATCH_TYPE_BY_MOD', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DISPATCH_TYPE_BY_RAND', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DISPATCH_TYPE_BY_CHASH', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DISPATCH_TYPE_BY_STICKY_SESSION', index=5, number=5,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DISPATCH_TYPE_BY_OBJECT', index=6, number=6,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=307,
  serialized_end=519,
)
_sym_db.RegisterEnumDescriptor(_DISPATCHTYPE)

DispatchType = enum_type_wrapper.EnumTypeWrapper(_DISPATCHTYPE)
DISPATCH_TYPE_NONE = 0
DISPATCH_TYPE_BY_ADDR = 1
DISPATCH_TYPE_BY_MOD = 2
DISPATCH_TYPE_BY_RAND = 3
DISPATCH_TYPE_BY_CHASH = 4
DISPATCH_TYPE_BY_STICKY_SESSION = 5
DISPATCH_TYPE_BY_OBJECT = 6



_PACKETHEAD = _descriptor.Descriptor(
  name='PacketHead',
  full_name='proto.PacketHead',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='packet_id', full_name='proto.PacketHead.packet_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sign_type', full_name='proto.PacketHead.sign_type', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sign', full_name='proto.PacketHead.sign', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='user_id', full_name='proto.PacketHead.user_id', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='src_addr', full_name='proto.PacketHead.src_addr', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='dst_addr', full_name='proto.PacketHead.dst_addr', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='dispatch_type', full_name='proto.PacketHead.dispatch_type', index=6,
      number=7, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='server_type', full_name='proto.PacketHead.server_type', index=7,
      number=8, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='dispatch_key_u64', full_name='proto.PacketHead.dispatch_key_u64', index=8,
      number=9, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='user_session_id', full_name='proto.PacketHead.user_session_id', index=9,
      number=10, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='id', full_name='proto.PacketHead.id', index=10,
      number=11, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='coroutine_id', full_name='proto.PacketHead.coroutine_id', index=11,
      number=12, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='hop_cnt', full_name='proto.PacketHead.hop_cnt', index=12,
      number=13, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='client_ip', full_name='proto.PacketHead.client_ip', index=13,
      number=14, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=304,
)

DESCRIPTOR.message_types_by_name['PacketHead'] = _PACKETHEAD
DESCRIPTOR.enum_types_by_name['DispatchType'] = _DISPATCHTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PacketHead = _reflection.GeneratedProtocolMessageType('PacketHead', (_message.Message,), {
  'DESCRIPTOR' : _PACKETHEAD,
  '__module__' : 'head_pb2'
  # @@protoc_insertion_point(class_scope:proto.PacketHead)
  })
_sym_db.RegisterMessage(PacketHead)


# @@protoc_insertion_point(module_scope)
