# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pb/player_data.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pb/player_data.proto',
  package='ProtoData',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x14pb/player_data.proto\x12\tProtoData\"*\n\x0cValkyrieData\x12\n\n\x02id\x18\x01 \x01(\r\x12\x0e\n\x06\x61mitie\x18\x02 \x01(\r\"%\n\x08TankData\x12\n\n\x02id\x18\x01 \x01(\r\x12\r\n\x05level\x18\x02 \x01(\r\"#\n\x08ItemData\x12\n\n\x02id\x18\x01 \x01(\r\x12\x0b\n\x03num\x18\x02 \x01(\r\"\x8e\x01\n\tPlayerBin\x12/\n\x0evalkyrie_datas\x18\x01 \x03(\x0b\x32\x17.ProtoData.ValkyrieData\x12\'\n\ntank_datas\x18\x02 \x03(\x0b\x32\x13.ProtoData.TankData\x12\'\n\nitem_datas\x18\x03 \x03(\x0b\x32\x13.ProtoData.ItemData\"\xde\x01\n\x08UserData\x12\x0b\n\x03uid\x18\x01 \x01(\r\x12\x10\n\x08username\x18\x02 \x01(\t\x12\x0f\n\x07stamina\x18\x03 \x01(\r\x12\x0c\n\x04gold\x18\x04 \x01(\r\x12\x0f\n\x07\x63rystal\x18\x05 \x01(\r\x12\x0c\n\x04wins\x18\x06 \x01(\r\x12\r\n\x05title\x18\x07 \x01(\t\x12\x0f\n\x07\x63omment\x18\x08 \x01(\t\x12(\n\nplayer_bin\x18\t \x01(\x0b\x32\x14.ProtoData.PlayerBin\x12\x13\n\x0b\x63reate_time\x18\n \x01(\t\x12\x16\n\x0eis_first_login\x18\x0b \x01(\x08\"L\n\x0bUserAccount\x12\x0b\n\x03uid\x18\x01 \x01(\r\x12\x10\n\x08username\x18\x02 \x01(\t\x12\x10\n\x08password\x18\x03 \x01(\t\x12\x0c\n\x04salt\x18\x04 \x01(\x0c\x62\x06proto3'
)




_VALKYRIEDATA = _descriptor.Descriptor(
  name='ValkyrieData',
  full_name='ProtoData.ValkyrieData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='ProtoData.ValkyrieData.id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='amitie', full_name='ProtoData.ValkyrieData.amitie', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=35,
  serialized_end=77,
)


_TANKDATA = _descriptor.Descriptor(
  name='TankData',
  full_name='ProtoData.TankData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='ProtoData.TankData.id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='level', full_name='ProtoData.TankData.level', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=79,
  serialized_end=116,
)


_ITEMDATA = _descriptor.Descriptor(
  name='ItemData',
  full_name='ProtoData.ItemData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='ProtoData.ItemData.id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='num', full_name='ProtoData.ItemData.num', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=118,
  serialized_end=153,
)


_PLAYERBIN = _descriptor.Descriptor(
  name='PlayerBin',
  full_name='ProtoData.PlayerBin',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='valkyrie_datas', full_name='ProtoData.PlayerBin.valkyrie_datas', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='tank_datas', full_name='ProtoData.PlayerBin.tank_datas', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='item_datas', full_name='ProtoData.PlayerBin.item_datas', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=156,
  serialized_end=298,
)


_USERDATA = _descriptor.Descriptor(
  name='UserData',
  full_name='ProtoData.UserData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='uid', full_name='ProtoData.UserData.uid', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='username', full_name='ProtoData.UserData.username', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='stamina', full_name='ProtoData.UserData.stamina', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='gold', full_name='ProtoData.UserData.gold', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='crystal', full_name='ProtoData.UserData.crystal', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='wins', full_name='ProtoData.UserData.wins', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='title', full_name='ProtoData.UserData.title', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='comment', full_name='ProtoData.UserData.comment', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='player_bin', full_name='ProtoData.UserData.player_bin', index=8,
      number=9, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='create_time', full_name='ProtoData.UserData.create_time', index=9,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='is_first_login', full_name='ProtoData.UserData.is_first_login', index=10,
      number=11, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=301,
  serialized_end=523,
)


_USERACCOUNT = _descriptor.Descriptor(
  name='UserAccount',
  full_name='ProtoData.UserAccount',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='uid', full_name='ProtoData.UserAccount.uid', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='username', full_name='ProtoData.UserAccount.username', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='password', full_name='ProtoData.UserAccount.password', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='salt', full_name='ProtoData.UserAccount.salt', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=525,
  serialized_end=601,
)

_PLAYERBIN.fields_by_name['valkyrie_datas'].message_type = _VALKYRIEDATA
_PLAYERBIN.fields_by_name['tank_datas'].message_type = _TANKDATA
_PLAYERBIN.fields_by_name['item_datas'].message_type = _ITEMDATA
_USERDATA.fields_by_name['player_bin'].message_type = _PLAYERBIN
DESCRIPTOR.message_types_by_name['ValkyrieData'] = _VALKYRIEDATA
DESCRIPTOR.message_types_by_name['TankData'] = _TANKDATA
DESCRIPTOR.message_types_by_name['ItemData'] = _ITEMDATA
DESCRIPTOR.message_types_by_name['PlayerBin'] = _PLAYERBIN
DESCRIPTOR.message_types_by_name['UserData'] = _USERDATA
DESCRIPTOR.message_types_by_name['UserAccount'] = _USERACCOUNT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ValkyrieData = _reflection.GeneratedProtocolMessageType('ValkyrieData', (_message.Message,), {
  'DESCRIPTOR' : _VALKYRIEDATA,
  '__module__' : 'pb.player_data_pb2'
  # @@protoc_insertion_point(class_scope:ProtoData.ValkyrieData)
  })
_sym_db.RegisterMessage(ValkyrieData)

TankData = _reflection.GeneratedProtocolMessageType('TankData', (_message.Message,), {
  'DESCRIPTOR' : _TANKDATA,
  '__module__' : 'pb.player_data_pb2'
  # @@protoc_insertion_point(class_scope:ProtoData.TankData)
  })
_sym_db.RegisterMessage(TankData)

ItemData = _reflection.GeneratedProtocolMessageType('ItemData', (_message.Message,), {
  'DESCRIPTOR' : _ITEMDATA,
  '__module__' : 'pb.player_data_pb2'
  # @@protoc_insertion_point(class_scope:ProtoData.ItemData)
  })
_sym_db.RegisterMessage(ItemData)

PlayerBin = _reflection.GeneratedProtocolMessageType('PlayerBin', (_message.Message,), {
  'DESCRIPTOR' : _PLAYERBIN,
  '__module__' : 'pb.player_data_pb2'
  # @@protoc_insertion_point(class_scope:ProtoData.PlayerBin)
  })
_sym_db.RegisterMessage(PlayerBin)

UserData = _reflection.GeneratedProtocolMessageType('UserData', (_message.Message,), {
  'DESCRIPTOR' : _USERDATA,
  '__module__' : 'pb.player_data_pb2'
  # @@protoc_insertion_point(class_scope:ProtoData.UserData)
  })
_sym_db.RegisterMessage(UserData)

UserAccount = _reflection.GeneratedProtocolMessageType('UserAccount', (_message.Message,), {
  'DESCRIPTOR' : _USERACCOUNT,
  '__module__' : 'pb.player_data_pb2'
  # @@protoc_insertion_point(class_scope:ProtoData.UserAccount)
  })
_sym_db.RegisterMessage(UserAccount)


# @@protoc_insertion_point(module_scope)
