# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pb/retcode.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pb/retcode.proto',
  package='proto',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x10pb/retcode.proto\x12\x05proto*A\n\x07Retcode\x12\x0c\n\x08RET_SUCC\x10\x00\x12\x0c\n\x08RET_FAIL\x10\x01\x12\x1a\n\x16RET_AUTHENTICATED_NEED\x10\x02\x62\x06proto3'
)

_RETCODE = _descriptor.EnumDescriptor(
  name='Retcode',
  full_name='proto.Retcode',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='RET_SUCC', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='RET_FAIL', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='RET_AUTHENTICATED_NEED', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=27,
  serialized_end=92,
)
_sym_db.RegisterEnumDescriptor(_RETCODE)

Retcode = enum_type_wrapper.EnumTypeWrapper(_RETCODE)
RET_SUCC = 0
RET_FAIL = 1
RET_AUTHENTICATED_NEED = 2


DESCRIPTOR.enum_types_by_name['Retcode'] = _RETCODE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


# @@protoc_insertion_point(module_scope)
